---
- name: Deploy AS3
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/bigip_creds.yaml
   
  vars:

  tasks:
    - name: Create a JIRA issue
      uri:
        url: https://18.132.111.108/mgmt/shared/appsvcs/declare
        user: "{{F5_user}}"
        password: "{{F5_pass}}"
        method: POST
        body: "{{ lookup('file','as3.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: no
      register: as3_response

    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: "{{as3_response}}"
    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: "Content Length = {{as3_response.content_length}}"

...